# Generated by Django 3.1.6 on 2021-06-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jenkinsjobmanage',
            old_name='stage_ip',
            new_name='pre_ip',
        ),
    ]
